### ISSUE TITLE
Registro de usuario

### ISSUE THREAD

**Issue by florpistan** [jgromerou/RollingAppRN#33]
## Proceso

1. Ingrese a la pagina.
2. Hice clic en Registrarse
3. Completé algunos campos del formulario

## Resultado esperado

- Por defecto, el botón Guardar se encuentra deshabilitando, evitando así que el usuario pueda hacer clic en "guardar" sin haber completado el formulario en su totalidad. Se habilita el botón únicamente cuando el usuario completó todos los campos requeridos para registrar un nuevo usuario

## Resultado obtenido

- El botón "Guardar" se habilita cuando el usuario completó todos los campos del formulario para el registro únicamente.

## Evidencia

![Screenshot_20231229_161946_Expo Go](https://github.com/jgromerou/RollingAppRN/assets/61049971/a7bf773b-29d0-404d-8c4a-61349325d122)

**Comment by herreranicolas** [comment]
Solucionado! Ahora el boton esta deshabilitado hasta que el usuario complete todos los campos obligatorios. 

![image](https://github.com/jgromerou/RollingAppRN/assets/96441102/791046f1-6177-483e-90a0-d26091699552)

**Comment by florpistan** [comment]
checked ✔
