### ISSUE TITLE
Checkout: Botón Pagar

### ISSUE THREAD

**Issue by florpistan** [jgromerou/RollingAppRN#34]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Añadí productos al carrito.
4. Me dirigí al carrito
5. Hice clic en "Confirmar"
6. Observé el botón "Pagar"

## Resultado esperado

- Se observa correctamente el botón pagar y su contenido

## Resultado obtenido

- La parte de abajo del texto del botón "pagar" se encuentra solapada.

## Evidencia

![Screenshot_20231229-194613](https://github.com/jgromerou/RollingAppRN/assets/61049971/d7759ed7-7b8d-4120-b3cd-d0d4f76610a2)

**Comment by lourdesgarciafyl** [comment]
Solucionado, cambiando el paddingVertical en el texto del botón. Muchas gracias

**Comment by florpistan** [comment]
checked ✔
