### ISSUE TITLE
Carrito Vacío

### ISSUE THREAD

**Issue by florpistan** [jgromerou/RollingAppRN#35]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Me dirigí al carrito sin items

## Resultado esperado

- Se observa un mensaje indicandole al usuario que no posee items en el carrito e invitando al usuario a navegar por nuestra página para ver nuestros productos

## Resultado obtenido

- No se observa ningún mensaje, se indica que se pagará $ 0

## Sugerencia

- Pueden observar en mercadolibre u otro e-commerce como se manejan los casos en los que el usuario no posee items en su carrito, les dejo acá un ejemplo:

<img width="488" alt="image" src="https://github.com/jgromerou/RollingAppRN/assets/61049971/5e0c0089-e5c8-4a17-9191-b57d77594c64">

## Evidencia
![Screenshot_20231229_171617_Expo Go](https://github.com/jgromerou/RollingAppRN/assets/61049971/24b808f9-0856-4a48-a3f7-e5618e802921)

**Comment by herreranicolas** [comment]
Solucionado! Ahora se muestra un mensaje cuando el usuario no agregó aún algun producto. 

![image](https://github.com/jgromerou/RollingAppRN/assets/96441102/6dd2ddc5-dbcd-4c89-9998-61d89b4e33be)

**Comment by florpistan** [comment]
checked ✔
