### ISSUE TITLE
Productos: Buscador

### ISSUE THREAD

**Issue by florpistan** [jgromerou/RollingAppRN#36]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Me dirigí al sector de productos
4. Ingresé una búsqueda que sé no arrojará resultados

## Resultado esperado

- Se observa un mensaje de error indicandole al usuario que su búsqueda no arrojo resultados.

## Resultado obtenido

- No se observa nada, ningún mensaje ni ningún producto ya que la búsqueda no arrojó resultados.

## Evidencia

https://github.com/jgromerou/RollingAppRN/assets/61049971/6f5b7b60-fea9-4e9a-960d-33e1bf19551d

**Comment by jgromerou** [comment]
Solucionado, se agregó un mensaje indicando que "no se encontraron productos" cuando se hace la búsqueda.

![mensajeBusquedaProductos](https://github.com/jgromerou/RollingAppRN/assets/46607767/9b07a113-0b5b-4da0-9c83-cca9014c181f)

**Comment by florpistan** [comment]
checked ✔
